Sprint1
ClevertecFrontendLab/sprint1-SergeyOrehov pull request #1
Opened 2023-01-31 23:08 UTC by SergeyOrehov

2023-01-31 23:10 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/SergeyOrehov/1675206653/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/SergeyOrehov/1675206653/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/SergeyOrehov/1675206653/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/SergeyOrehov/1675206653/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/SergeyOrehov/1675206653/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/SergeyOrehov/1675206653/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/SergeyOrehov/1675206653/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/SergeyOrehov/1675206653/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/SergeyOrehov/1675206653/content-window.png)

2023-02-01 06:06 UTC, Gaurrus requested changes

2023-02-01 06:06 UTC, Gaurrus commented on src/index.css
> +}
это убирай, скриншоты станут нормальные

2023-02-01 08:48 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/SergeyOrehov/1675241309/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/SergeyOrehov/1675241309/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/SergeyOrehov/1675241309/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/SergeyOrehov/1675241309/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/SergeyOrehov/1675241309/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/SergeyOrehov/1675241309/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/SergeyOrehov/1675241309/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/SergeyOrehov/1675241309/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/SergeyOrehov/1675241309/content-window.png)

2023-02-01 12:17 UTC, Gaurrus approved these changes

2023-02-01 12:17 UTC, Gaurrus commented on src/components/layout/styles.scss
> +  height: 100vh;
всё по верстке норм `min-height: 100vh;` еще вот тут чтобы скриншоты были норм. И файлы стилей именуй прям как файл компонента к которому он относится, так понятней что от чего)

2023-02-01 12:17 UTC, Gaurrus commented on src/components/app/app.tsx
> +// components
не надо подписывать ничего) все именуется так что сразу понятнол где компоненты где переменные или функции и типы)

2023-02-01 12:17 UTC, Gaurrus commented on src/components/books-list/styles.scss
> +
пустые файлы не оставляют

2023-02-01 12:23 UTC, merged